services:
  postgres:
    image: postgres:16
    container_name: traintracker-postgres
    environment:
      POSTGRES_DB: traintracker
      POSTGRES_USER: traintracker_user
      POSTGRES_PASSWORD: traintracker_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: