services:
  postgres:
    image: postgres:16
    container_name: traintracker-postgres
    environment:
      POSTGRES_DB: traintracker
      POSTGRES_USER: traintracker_user
      POSTGRES_PASSWORD: traintracker_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: traintracker-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/traintracker
      SPRING_DATASOURCE_USERNAME: traintracker_user
      SPRING_DATASOURCE_PASSWORD: traintracker_pass
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION_MINUTES: 60

volumes:
  postgres_data: