create table route
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

create table station
(
    id   bigint generated by default as identity
        primary key,
    city varchar(255) not null,
    name varchar(255) not null
);

create table route_station
(
    id                 bigint generated by default as identity
        primary key,
    minutes_from_start integer not null,
    stop_order         integer not null,
    route_id           bigint  not null
        constraint fk_route_station_route
            references route,
    station_id         bigint  not null
        constraint fk_route_station_station
            references station
);

create table train
(
    id             bigint generated by default as identity
        primary key,
    bogeys         integer      not null,
    seats_by_bogey integer      not null,
    type           varchar(255) not null
);

create table trip
(
    id             bigint generated by default as identity
        primary key,
    departure_time timestamp(6)  not null,
    seats          varchar(1000) not null,
    status         varchar(255)  not null
        constraint trip_status_check
            check ((status)::text = ANY
        ((ARRAY ['ON_TIME'::character varying, 'DELAYED'::character varying, 'CANCELLED'::character varying])::text[])),
    version        bigint        not null,
    route_id       bigint        not null
        constraint fk_trip_route
            references route,
    train_id       bigint        not null
        constraint fk_trip_train
            references train
);

create table users
(
    id           bigint generated by default as identity
        primary key,
    dni          varchar(255) not null
        constraint uk_users_dni
            unique,
    email        varchar(255) not null
        constraint uk_users_email
            unique,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    password     varchar(255) not null,
    phone_number varchar(255) not null
        constraint uk_users_phone_number
            unique,
    role         varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[]))
    );

create table ticket
(
    id             bigint generated by default as identity
        primary key,
    bogey          integer          not null,
    price          double precision not null,
    seat           integer          not null,
    uuid           varchar(255)     not null
        constraint uk_ticket_uuid
            unique,
    destination_id bigint           not null
        constraint fk_ticket_destination_station
            references station,
    origin_id      bigint           not null
        constraint fk_ticket_origin_station
            references station,
    trip_id        bigint           not null
        constraint fk_ticket_trip
            references trip,
    user_id        bigint           not null
        constraint fk_ticket_user
            references users
);