spring:
  application:
    name: traintracker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/traintracker}
    username: ${SPRING_DATASOURCE_USERNAME:traintracker_user}
    password: ${SPRING_DATASOURCE_PASSWORD:traintracker_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: ${JWT_KEY:Opf43RpRrQ4+w6CIQAZqJNRL6JnY56O9OlJ9Nx9DsY8=}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

server:
  port: ${PORT:8080}
