spring:
  application:
    name: traintracker
  datasource:
    url: jdbc:postgresql://localhost:5433/traintracker
    username: traintracker_user
    password: traintracker_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080