spring:
  application:
    name: traintracker
  datasource:
    url: jdbc:postgresql://localhost:5433/traintracker
    username: traintracker_user
    password: traintracker_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: "Opf43RpRrQ4+w6CIQAZqJNRL6JnY56O9OlJ9Nx9DsY8="
  expiration-minutes: 60

server:
  port: 8080